CREATE TABLE "GCG_4831_PartWF"(
 "ECN_NUMBER" NUMERIC(20,0),
 "PART" CHAR(17),
 "REV" CHAR(3),
 "LOC" CHAR(2),
 "PART_DESC" CHAR(30),
 "REQ" CHAR(25),
 "REQ_DESC" CHAR(50),
 "SHIPPING_HOLD" CHAR(1),
 "WO_HOLD" CHAR(1),
 "DATE_TIME" CHAR(20),
 "THEUSER" CHAR(6),
 "DATE_TIME2" CHAR(50),
 "THEUSER2" CHAR(50));
